export const FANSIGNUP_SUCCESS = "FANSIGNUP_SUCCESS";
export const FANSIGNUP_FALL = "FANSIGNUP_FALL";
export const SIGNUP = "SIGNUP";
export const TALENTSIGNUP_SUCCESS = "TALENTSIGNUP_SUCCESS";
export const TALENTSIGNUP_FALL = "TALENTSIGNUP_FAIL";
